name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev \
            libjpeg-dev zlib1g-dev libsqlite3-dev curl

          pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK + AIDL
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools

          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip tools.zip -d latest
          rm tools.zip

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.2"

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

          cd EmployeeTrackerApp  # 🔁 replace with your app folder name
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
