name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev \
            libjpeg-dev zlib1g-dev libsqlite3-dev curl

          pip install --upgrade pip
          pip install buildozer cython

      - name: Download Android SDK Command-line Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/temp
          mv $ANDROID_SDK_ROOT/cmdline-tools/temp/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm -rf $ANDROID_SDK_ROOT/cmdline-tools/temp tools.zip

      - name: Install Android SDK Packages
        run: |
          echo "PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.2"

      - name: Build APK
        run: |
          
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: employee-tracker-apk
          path: EmployeeTrackerApp/bin/*.apk
