name: Build Employee Tracker APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          unzip \
          python3-pip \
          git \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          zlib1g-dev \
          libreadline-dev \
          libgdbm-dev \
          libbz2-dev \
          liblzma-dev \
          libgmp-dev

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK & NDK
      run: |
        mkdir -p $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0" \
          "ndk;23.1.7779620"

    - name: Set environment variables
      run: |
        echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=$HOME/android-sdk/ndk/23.1.7779620" >> $GITHUB_ENV
        echo "ANDROIDAPI=31" >> $GITHUB_ENV
        echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: EmployeeTracker-APK
        path: bin/*.apk
