name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool libtool-bin autotools-dev

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-for-android kivy pandas

      - name: Build with python-for-android
        run: |
          python -m pythonforandroid.toolchain create --dist_name=employeetracker --bootstrap=sdl2 --requirements=python3,kivy,pandas --arch=arm64-v8a --arch=armeabi-v7a --copy-libs --color=always --storage-dir=.buildozer/android/platform/build-arm64-v8a_armeabi-v7a --ndk-api=21 --ignore-setup-py --debug
