name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip git \
          autoconf automake libtool libtool-bin pkg-config build-essential

    - name: Upgrade pip, install Buildozer & dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade buildozer python-for-android cython

    - name: Regenerate configure scripts if present
      run: |
        if [ -f configure.ac ]; then
          autoreconf --install --force
        fi

    - name: Install Android Command-line Tools
      run: |
       mkdir -p $HOME/android-sdk/cmdline-tools
       cd $HOME/android-sdk/cmdline-tools
       curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
       unzip commandlinetools.zip
       rm commandlinetools.zip
       mv cmdline-tools latest
       yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
       $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;26.1.10909125"
       env:
       ANDROID_HOME: $HOME/android-sdk


    - name: Clean Buildozer build
      run: buildozer android clean

    - name: Build APK with Buildozer
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROID_SDK_ROOT: $HOME/android-sdk
        PATH: $HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:${PATH}
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: employee-tracker-apk
        path: bin/*.apk
