name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-17-jdk python3-pip python3-setuptools \
            libssl-dev libffi-dev libsqlite3-dev zlib1g-dev \
            libbz2-dev libreadline-dev liblzma-dev \
            libncurses5-dev libncursesw5-dev

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython virtualenv buildozer

      - name: Initialize buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Configure buildozer.spec
        run: |
          sed -i 's/^# *android.api =.*/android.api = 31/' buildozer.spec
          sed -i 's/^# *android.build_tools_version =.*/android.build_tools_version = 31.0.0/' buildozer.spec
          sed -i 's/^# *android.minapi =.*/android.minapi = 21/' buildozer.spec
          sed -i 's/^# *android.permissions =.*/android.permissions = INTERNET/' buildozer.spec

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EmployeeTracker-APK
          path: bin/*.apk
