name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install required system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          zlib1g-dev \
          libncursesw5-dev \
          libreadline-dev \
          tar \
          unzip \
          curl

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK
      run: |
        sudo apt-get install -y openjdk-11-jdk
        buildozer android debug
