name: Build Employee Tracker APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool pkg-config \
          unzip zip git openjdk-17-jdk \
          python3-pip python3-setuptools python3-wheel \
          libffi-dev libssl-dev libsqlite3-dev zlib1g-dev \
          libncurses5 libncurses5-dev libtinfo5 cmake

    - name: Install Buildozer & dependencies
      run: |
        pip install --upgrade pip Cython virtualenv
        pip install buildozer python-for-android

    - name: Prepare Android SDK & NDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip -d latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

    - name: Build APK
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROIDNDK: $HOME/android-sdk/ndk/25.2.9519653
        PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: EmployeeTracker-APK
        path: bin/*.apk
