name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          ccache \
          libncursesw5 \
          libstdc++6 \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          liblzma-dev \
          unzip \
          openjdk-11-jdk \
          git \
          tar \
          zip \
          curl

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK
      run: |
        buildozer init || true
        buildozer android debug
