name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip git \
          autoconf automake libtool libtool-bin pkg-config build-essential

    - name: Upgrade pip, install Buildozer & dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade buildozer python-for-android cython

    - name: Regenerate configure scripts if present
      run: |
        if [ -f configure.ac ]; then
          autoreconf --install --force
        fi

    - name: Install Android SDK (command line tools)
      env:
        ANDROID_SDK_ROOT: $HOME/android-sdk
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        # Fix nested cmdline-tools directory
        if [ -d latest/cmdline-tools ]; then
          mv latest/cmdline-tools/* latest/
          rmdir latest/cmdline-tools
        fi
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        which sdkmanager || echo "sdkmanager not found"
        ls -l $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
        yes | sdkmanager --licenses
        sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Clean Buildozer build
      run: buildozer android clean

    - name: Build APK with Buildozer
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROID_SDK_ROOT: $HOME/android-sdk
        PATH: $HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:${PATH}
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: employee-tracker-apk
        path: bin/*.apk
