name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            zip \
            unzip \
            libstdc++6 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            git \
            openjdk-17-jdk \
            python3-pip

      - name: Install Cython and Buildozer
        run: |
          pip install --upgrade pip Cython==0.29.36
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug
